### ISSUE TITLE
Create a Node.js web server with Express Framework

### ISSUE THREAD

**Issue by jesse-crypted** [The-Complete-Hub/writers-program#3]
**Writing sample(s):**  [Hosted on the dev community](https://dev.to/jessecrypted/i-created-a-web-server-4dc0)

**Proposed title of the article:** Create a Node.js web server with Express Framework

**Proposed article introduction:**
Node.js is a javascript framework that allows us to run javascript outside the browser, it is a javascript runtime built on chrome v8 engine.
Skipping the not-so-boring stuff we will be trying our hands at building a simple web server using a popular javascript framework called 'Express'. Express is a framework that gives node.js superpowers because of its amazing feature.

**Key takeaways:**

- Readers who are not familiar with node.js should develop an interest in learning more about node.js and express.
- Readers should understand the concept of request and response in node.js.
- Readers should be able to understand this article and code along.

**References:** [Express documentation](https://expressjs.com/en/starter/hello-world.html)

**Comment by Favour-dgreat** [comment]
Great. You can go ahead with this article. I will be here if you need my help at any time. 
Kindly look at the article example provided in the contents/articles directory.
